In [1]:
import numpy as np

In [5]:
#return array with ten zeros
np.zeros((10), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#return array with ten fives
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [8]:
#return array with values from 10 do 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [13]:
#return matrix 3x3 with numbers from 0 to 8

#np.matrix('0,1,2;3,4,5;6,7,8')
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#return unit matrix

#np.identity(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#return array 10x10 from 0.01 to 1 with step 0.01
np.arange(0.01, 1.01, 0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [20]:
#return array with 20 linerly spaced numbers from 0 to 1(incuding 0 and 1)
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [67]:
#return array with random number from 1 to 25 reshaped into matrix 5x5
a = np.random.randint(1,25,size = (5,5))

print(a)

print('sum of matrix elements:', a.sum())

print('avarage of matrix elements:', a.mean())

print('sum of matrix columns:', a.sum(0))

#array1 = []
#col1 = a[:,0].sum()
#col2 = a[:,1].sum()
#col3 = a[:,2].sum()
#col4 = a[:,3].sum()
#col5 = a[:,4].sum()
#array1 = col1,col2,col3,col4,col5
#print('sum of matrix columns:', array1)


[[ 3 15  6  3  3]
 [19  9  2 22 17]
 [ 9 14  6  7  3]
 [20  2 18  8 12]
 [ 4 22  4  6  6]]
sum of matrix elements: 240
avarage of matrix elements: 9.6
sum of matrix columns: [55 62 36 46 41]


2

In [72]:
#return a min value from matrix
b = np.random.randint(0,101,size=(5,5))
print(b)
print('median of matrix:', np.median(b))
print('min value from matrix:',b.min())
print('max value from matrix:',b.max())

[[78 85 21 38 56]
 [98 72 29 93 65]
 [41 80 92 94 81]
 [12 25 62 14 37]
 [30 44 50 87  3]]
min value from matrix: 3
max value from matrix: 98
median of matrix: 56.0


In [78]:
#return transposed matrix with different dimensions
c = np.random.randint(0,101, size=(3,5))
print(c,'\n')
print('transposed matrix:\n', c.transpose())

[[36 35 38 56 32]
 [ 5 34 71 84 70]
 [ 5 10 69 88  9]] 

transposed matrix:
 [[36  5  5]
 [35 34 10]
 [38 71 69]
 [56 84 88]
 [32 70  9]]
